### ISSUE TITLE
Can't show failed test correctly 

### ISSUE THREAD

**Issue by valenso** [fnando/minitest-utils#3]
I get

```
Failed Tests:
/Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-utils-0.1.3/lib/minitest/utils/reporter.rb:107:in `find_test_file': undefined method `gsub' for nil:NilClass (NoMethodError)
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-utils-0.1.3/lib/minitest/utils/reporter.rb:96:in `display_replay_command'
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-utils-0.1.3/lib/minitest/utils/reporter.rb:49:in `block in report'
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-utils-0.1.3/lib/minitest/utils/reporter.rb:49:in `each'
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-utils-0.1.3/lib/minitest/utils/reporter.rb:49:in `report'
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-5.6.1/lib/minitest.rb:638:in `each'
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-5.6.1/lib/minitest.rb:638:in `report'
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-5.6.1/lib/minitest.rb:134:in `run'
    from /Users/valentin/.rvm/gems/ruby-2.2.1/gems/minitest-5.6.1/lib/minitest.rb:56:in `block in autorun'
```

When I try

```
class SampleTest < Minitest::Test
  test 'useless test' do
    assert false
  end
end
```

**Comment by valenso** [comment]
I solve it
my test folder names "tests", just rename it
